### ISSUE TITLE
Error upon connecting database

### ISSUE THREAD

**Issue by techuila** [SwitchQL/SwitchQL#29]
Uncaught Exception:
TypeError: Cannot read property 'name' of undefined at socket.<anonymous>

**Comment by laueian** [comment]
Hi techuila,

Thank you for raising the issue. Can you provide us with some information please.

Which branch did you deploy from?
Which platform are you on (Win, Linux, OSX)?
What database are you attempting to connect to (postgres, mysql, etc..)?

**Comment by laueian** [comment]
We did our first official release today. Please try out the download and let us know how it goes :) 

https://github.com/SwitchQL/SwitchQL/releases
